function uuidv4() {
  return ([1e7] + -1e3 + -4e3 + -8e3 + -1e11).replace(/[018]/g, (c) =>
    (
      c ^
      (crypto.getRandomValues(new Uint8Array(1))[0] & (15 >> (c / 4)))
    ).toString(16)
  );
}

function postMessgae(
  pName,
  pNationality,
  pAge,
  pEmirate,
  pMessage_Body,
  pPhoneNumber
) {
  const tData = {
    gender: "",
    email: "",
    id: uuidv4(),
    name: pName,
    age: parseInt(pAge),
    message_Body: pMessage_Body,
    phoneNumber: pPhoneNumber,
    nationality: pNationality,
    emirate: pEmirate,
  };

  var xhr = new XMLHttpRequest();
  xhr.open("POST", "http://94.127.214.136:5343/MAM/sendMessage/", true);
  xhr.setRequestHeader("Content-Type", "application/json");
  xhr.send(JSON.stringify(tData));
}

function next1() {
  var page1 = document.getElementById("page-1");
  var page2 = document.getElementById("page-2");
  var page3 = document.getElementById("page-3");
  var page4 = document.getElementById("page-4");
  page1.style.display = "none";
  page2.style.display = "block";
  page3.style.display = "none";
  page4.style.display = "none";
}

function next2() {
  var page1 = document.getElementById("page-1");
  var page2 = document.getElementById("page-2");
  var page3 = document.getElementById("page-3");
  var page4 = document.getElementById("page-4");

  page1.style.display = "none";
  page2.style.display = "none";
  page3.style.display = "block";
  page4.style.display = "none";

  var nationality = document.getElementById("nationality");
  var emirate = document.getElementById("emirate");
  httpGet();
  //Create and append the options
  for (var i = 0; i < tNationalits.length; i++) {
    var option = document.createElement("option");
    option.value = tNationalits[i].code;
    option.text = tNationalits[i].text;
    nationality.appendChild(option);
  }

  for (var i = 0; i < tEmirates.length; i++) {
    var option = document.createElement("option");
    option.value = tEmirates[i];
    option.text = tEmirates[i];
    emirate.appendChild(option);
  }
}

function next3() {
  var page1 = document.getElementById("page-1");
  var page2 = document.getElementById("page-2");
  var page3 = document.getElementById("page-3");
  var page4 = document.getElementById("page-4");

  page1.style.display = "none";
  page2.style.display = "none";
  page3.style.display = "none";
  page4.style.display = "block";

  var name = document.getElementById("name");
  var age = document.getElementById("age");
  var phone = document.getElementById("phone");
  var emirate = document.getElementById("emirate");

  var name = document.getElementById("name").value;
  var age = document.getElementById("age").value;
  var phone = document.getElementById("phone").value;
  var emirate = document.getElementById("emirate").value;
  var nationality = document.getElementById("nationality").value;
  var textarea = document.getElementById("textarea").value;

  postMessgae(name, nationality, age, emirate, textarea, phone);
}

function httpGet() {
  for (let index = 0; index < nationalits.countries.length; index++) {
    const value = nationalits.countries[index].country_arName;
    const code = nationalits.countries[index].country_code;
    tNationalits.push({ text: value, code: code });
  }
  for (let index = 0; index < emirates.em.length; index++) {
    const element = emirates.em[index].text.split("|")[1];
    tEmirates.push(element);
  }
}

var nationalits = {
  countries: [
    {
      id: "196c1b6e-a231-4286-b6ed-a8a508296eb3",
      country_code: "AE",
      country_enName: "United Arab Emirates",
      country_arName: "الإمارات العربية المتحدة",
      country_enNationality: "Emirati",
      country_arNationality: "إماراتي",
    },
    {
      id: "b53a5cdf-19a7-4cde-b331-00313d4790bd",
      country_code: "IT",
      country_enName: "Italy",
      country_arName: "إيطاليا",
      country_enNationality: "Italian",
      country_arNationality: "إيطالي",
    },
    {
      id: "831961f1-e232-4455-810f-00e225b8c1a3",
      country_code: "NC",
      country_enName: "New Caledonia",
      country_arName: "كاليدونيا الجديدة",
      country_enNationality: "New Caledonian",
      country_arNationality: "كاليدوني",
    },
    {
      id: "ac492456-4eca-4594-b4e9-01de772536af",
      country_code: "CU",
      country_enName: "Cuba",
      country_arName: "كوبا",
      country_enNationality: "Cuban",
      country_arNationality: "كوبي",
    },
    {
      id: "69d5bb81-2250-4cc0-810f-0305617cf002",
      country_code: "YT",
      country_enName: "Mayotte",
      country_arName: "مايوت",
      country_enNationality: "Mahoran",
      country_arNationality: "مايوتي",
    },
    {
      id: "ecd5b45d-9873-401f-891e-035a56879f32",
      country_code: "TC",
      country_enName: "Turks and Caicos Islands",
      country_arName: "جزر توركس وكايكوس",
      country_enNationality: "Turks and Caicos Islands",
      country_arNationality: "جزر توركس وكايكوس",
    },
    {
      id: "709c434d-ff3e-4090-95e3-03e36a343fe1",
      country_code: "UZ",
      country_enName: "Uzbekistan",
      country_arName: "أوزباكستان",
      country_enNationality: "Uzbek",
      country_arNationality: "أوزباكستاني",
    },
    {
      id: "23290b1c-57a8-4f1d-9d6e-04345493b198",
      country_code: "CR",
      country_enName: "Costa Rica",
      country_arName: "كوستاريكا",
      country_enNationality: "Costa Rican",
      country_arNationality: "كوستاريكي",
    },
    {
      id: "6839108a-6dd0-4634-8f3d-05d4e0e7391a",
      country_code: "MR",
      country_enName: "Mauritania",
      country_arName: "موريتانيا",
      country_enNationality: "Mauritanian",
      country_arNationality: "موريتانيي",
    },
    {
      id: "7b4967f7-3a8f-49da-a96a-0623a146ce9b",
      country_code: "RS",
      country_enName: "Serbia",
      country_arName: "صربيا",
      country_enNationality: "Serbian",
      country_arNationality: "صربي",
    },
    {
      id: "9ecd147b-105f-4722-9a96-064cf39019c7",
      country_code: "GM",
      country_enName: "Gambia",
      country_arName: "غامبيا",
      country_enNationality: "Gambian",
      country_arNationality: "غامبي",
    },
    {
      id: "c38c2b8c-30f7-4576-9601-09d7216e4571",
      country_code: "IM",
      country_enName: "Isle of Man",
      country_arName: "جزيرة مان",
      country_enNationality: "Manx",
      country_arNationality: "ماني",
    },
    {
      id: "a9828e5e-6bf8-4204-b010-09ed615016c9",
      country_code: "EC",
      country_enName: "Ecuador",
      country_arName: "إكوادور",
      country_enNationality: "Ecuadorian",
      country_arNationality: "إكوادوري",
    },
    {
      id: "aaf8d60b-0a12-44bd-bd01-0a7c729dba15",
      country_code: "AW",
      country_enName: "Aruba",
      country_arName: "أروبه",
      country_enNationality: "Aruban",
      country_arNationality: "أوروبهيني",
    },
    {
      id: "2c050446-c0a7-47ee-a983-0b130c3ca94a",
      country_code: "SL",
      country_enName: "Sierra Leone",
      country_arName: "سيراليون",
      country_enNationality: "Sierra Leonean",
      country_arNationality: "سيراليوني",
    },
    {
      id: "c855ad59-2303-4a96-b78c-0b3d976026f5",
      country_code: "KH",
      country_enName: "Cambodia",
      country_arName: "كمبوديا",
      country_enNationality: "Cambodian",
      country_arNationality: "كمبودي",
    },
    {
      id: "e2b982de-e747-4796-ab0d-0c0d57fa4ef0",
      country_code: "LC",
      country_enName: "Saint Pierre and Miquelon",
      country_arName: "سان بيير وميكلون",
      country_enNationality: "St. Pierre and Miquelon",
      country_arNationality: "سان بيير وميكلوني",
    },
    {
      id: "2acf6e3c-625c-4662-bf60-0c7a531657ec",
      country_code: "IE",
      country_enName: "Ireland",
      country_arName: "إيرلندا",
      country_enNationality: "Irish",
      country_arNationality: "إيرلندي",
    },
    {
      id: "d46f3e9a-89d7-4001-a579-0ce502f9f5c3",
      country_code: "PH",
      country_enName: "Philippines",
      country_arName: "الفليبين",
      country_enNationality: "Filipino",
      country_arNationality: "فلبيني",
    },
    {
      id: "348663e9-afe8-4d36-97ff-0effdeea3952",
      country_code: "SO",
      country_enName: "Somalia",
      country_arName: "الصومال",
      country_enNationality: "Somali",
      country_arNationality: "صومالي",
    },
    {
      id: "61a03737-1cb1-4674-a69f-102bd4f32306",
      country_code: "LA",
      country_enName: "Lao PDR",
      country_arName: "لاوس",
      country_enNationality: "Laotian",
      country_arNationality: "لاوسي",
    },
    {
      id: "e1922eeb-8635-4050-9ff6-134f3455e72e",
      country_code: "JM",
      country_enName: "Jamaica",
      country_arName: "جمايكا",
      country_enNationality: "Jamaican",
      country_arNationality: "جمايكي",
    },
    {
      id: "f12da1aa-8616-40bb-bab0-15fab7fb92cb",
      country_code: "CN",
      country_enName: "China",
      country_arName: "الصين",
      country_enNationality: "Chinese",
      country_arNationality: "صيني",
    },
    {
      id: "6610ab60-2291-43d4-956b-17585f4a4d50",
      country_code: "SG",
      country_enName: "Singapore",
      country_arName: "سنغافورة",
      country_enNationality: "Singaporean",
      country_arNationality: "سنغافوري",
    },
    {
      id: "9870bb4d-4450-4f8e-9c72-17b27abd46b4",
      country_code: "TW",
      country_enName: "Taiwan",
      country_arName: "تايوان",
      country_enNationality: "Taiwanese",
      country_arNationality: "تايواني",
    },
    {
      id: "10b036ba-f1bd-4ac5-9b63-19e73df9f402",
      country_code: "JO",
      country_enName: "Jordan",
      country_arName: "الأردن",
      country_enNationality: "Jordanian",
      country_arNationality: "أردني",
    },
    {
      id: "38acb3b1-2896-4151-b7b9-1a11562f5123",
      country_code: "VA",
      country_enName: "Vatican City",
      country_arName: "فنزويلا",
      country_enNationality: "Vatican",
      country_arNationality: "فاتيكاني",
    },
    {
      id: "b5d62a95-6137-4d30-99c6-20ce3653420a",
      country_code: "GA",
      country_enName: "Gabon",
      country_arName: "الغابون",
      country_enNationality: "Gabonese",
      country_arNationality: "غابوني",
    },
    {
      id: "fc814b0f-3d99-4589-9338-21cf4469e26d",
      country_code: "IN",
      country_enName: "India",
      country_arName: "الهند",
      country_enNationality: "Indian",
      country_arNationality: "هندي",
    },
    {
      id: "62f25c84-ad10-40a0-ba2e-21d0425453da",
      country_code: "SE",
      country_enName: "Sweden",
      country_arName: "السويد",
      country_enNationality: "Swedish",
      country_arNationality: "سويدي",
    },
    {
      id: "f87c4747-b90c-4a31-ac85-2247fbd15166",
      country_code: "AO",
      country_enName: "Angola",
      country_arName: "أنغولا",
      country_enNationality: "Angolan",
      country_arNationality: "أنقولي",
    },
    {
      id: "71f4afdd-c6df-40f2-9d05-233635b309e9",
      country_code: "AL",
      country_enName: "Albania",
      country_arName: "ألبانيا",
      country_enNationality: "Albanian",
      country_arNationality: "ألباني",
    },
    {
      id: "4372282a-9150-437b-bd14-23775ddabe6f",
      country_code: "AR",
      country_enName: "Argentina",
      country_arName: "الأرجنتين",
      country_enNationality: "Argentinian",
      country_arNationality: "أرجنتيني",
    },
    {
      id: "5da5d8ee-2fe3-4e48-a7ec-246ce6d3b917",
      country_code: "MQ",
      country_enName: "Martinique",
      country_arName: "مارتينيك",
      country_enNationality: "Martiniquais",
      country_arNationality: "مارتينيكي",
    },
    {
      id: "c18d60ef-4e88-42b6-8af7-24dfb4c867ac",
      country_code: "VI",
      country_enName: "Virgin Islands (U.S.)",
      country_arName: "الجزر العذراء الأمريكي",
      country_enNationality: "American Virgin Islander",
      country_arNationality: "أمريكي",
    },
    {
      id: "f154a24b-e29e-4169-b2b0-266305cc14d2",
      country_code: "PT",
      country_enName: "Portugal",
      country_arName: "البرتغال",
      country_enNationality: "Portuguese",
      country_arNationality: "برتغالي",
    },
    {
      id: "d499ff58-4712-4882-86eb-27021288ec46",
      country_code: "KI",
      country_enName: "Kiribati",
      country_arName: "كيريباتي",
      country_enNationality: "I-Kiribati",
      country_arNationality: "كيريباتي",
    },
    {
      id: "cce65d0b-9d95-498e-83ec-27da840d0b2d",
      country_code: "KG",
      country_enName: "Kyrgyzstan",
      country_arName: "قيرغيزستان",
      country_enNationality: "Kyrgyzstani",
      country_arNationality: "قيرغيزستاني",
    },
    {
      id: "f5cccb57-16e3-4d14-9a31-285f58717afa",
      country_code: "CK",
      country_enName: "Cook Islands",
      country_arName: "جزر كوك",
      country_enNationality: "Cook Islander",
      country_arNationality: "جزر كوك",
    },
    {
      id: "f946711d-5eff-4e5b-8c2b-2b1b107b61a7",
      country_code: "FI",
      country_enName: "Finland",
      country_arName: "فنلندا",
      country_enNationality: "Finnish",
      country_arNationality: "فنلندي",
    },
    {
      id: "6bc07546-8230-47cf-a293-2b8e86786883",
      country_code: "MD",
      country_enName: "Moldova",
      country_arName: "مولدافيا",
      country_enNationality: "Moldovan",
      country_arNationality: "مولديفي",
    },
    {
      id: "09d4f3b1-495c-4391-85c4-2c4de513719f",
      country_code: "VU",
      country_enName: "Vanuatu",
      country_arName: "فانواتو",
      country_enNationality: "Vanuatuan",
      country_arNationality: "فانواتي",
    },
    {
      id: "40c54917-7b0b-468c-9b1e-2c7832d10bb0",
      country_code: "PY",
      country_enName: "Paraguay",
      country_arName: "باراغواي",
      country_enNationality: "Paraguayan",
      country_arNationality: "بارغاوي",
    },
    {
      id: "e77e3113-e411-405d-9fd3-2de1badb1b3d",
      country_code: "PN",
      country_enName: "Pitcairn",
      country_arName: "بيتكيرن",
      country_enNationality: "Pitcairn Islander",
      country_arNationality: "بيتكيرني",
    },
    {
      id: "4b3712b6-a20d-46b1-8fa7-2e22e150e796",
      country_code: "GW",
      country_enName: "Guinea-Bissau",
      country_arName: "غينيا-بيساو",
      country_enNationality: "Guinea-Bissauan",
      country_arNationality: "غيني",
    },
    {
      id: "cd9cab9c-2c95-4612-823a-2e47dc89f14b",
      country_code: "ME",
      country_enName: "Montenegro",
      country_arName: "الجبل الأسود",
      country_enNationality: "Montenegrin",
      country_arNationality: "الجبل الأسود",
    },
    {
      id: "d674a2bb-7822-49f7-a734-2f87cf1ac40f",
      country_code: "US",
      country_enName: "United States",
      country_arName: "الولايات المتحدة",
      country_enNationality: "American",
      country_arNationality: "أمريكي",
    },
    {
      id: "552dc69f-360f-4009-b624-2fc6d4dade28",
      country_code: "NA",
      country_enName: "Namibia",
      country_arName: "ناميبيا",
      country_enNationality: "Namibian",
      country_arNationality: "ناميبي",
    },
    {
      id: "43e8ca10-7e51-40f0-939d-346dd147ee25",
      country_code: "NF",
      country_enName: "Norfolk Island",
      country_arName: "جزيرة نورفولك",
      country_enNationality: "Norfolk Islander",
      country_arNationality: "نورفوليكي",
    },
    {
      id: "40c65472-46ef-4276-a8fb-3494ea341084",
      country_code: "NO",
      country_enName: "Norway",
      country_arName: "النرويج",
      country_enNationality: "Norwegian",
      country_arNationality: "نرويجي",
    },
    {
      id: "cc6521ee-3f49-4361-a016-380d988a1159",
      country_code: "CH",
      country_enName: "Switzerland",
      country_arName: "سويسرا",
      country_enNationality: "Swiss",
      country_arNationality: "سويسري",
    },
    {
      id: "18d48f82-5e06-4fe2-a699-396832d40363",
      country_code: "HN",
      country_enName: "Honduras",
      country_arName: "هندوراس",
      country_enNationality: "Honduran",
      country_arNationality: "هندوراسي",
    },
    {
      id: "24b62dd6-a597-4981-88f4-396eccc856c3",
      country_code: "MF",
      country_enName: "Saint Martin (French part)",
      country_arName: "ساينت مارتن فرنسي",
      country_enNationality: "St. Martian(French)",
      country_arNationality: "ساينت مارتني فرنسي",
    },
    {
      id: "eea5ce29-1155-4d32-80d2-3a27d04016e6",
      country_code: "SA",
      country_enName: "Saudi Arabia",
      country_arName: "المملكة العربية السعودية",
      country_enNationality: "Saudi Arabian",
      country_arNationality: "سعودي",
    },
    {
      id: "32f5fdbc-407b-4698-b7bd-3d7169ba2814",
      country_code: "KZ",
      country_enName: "Kazakhstan",
      country_arName: "كازاخستان",
      country_enNationality: "Kazakh",
      country_arNationality: "كازاخستاني",
    },
    {
      id: "caa1aed3-3dd4-41ee-8097-3e38a80533e9",
      country_code: "BN",
      country_enName: "Brunei Darussalam",
      country_arName: "بروني",
      country_enNationality: "Bruneian",
      country_arNationality: "بروني",
    },
    {
      id: "d05834c4-998b-4f0a-8702-3e5b6946f616",
      country_code: "SB",
      country_enName: "Solomon Islands",
      country_arName: "جزر سليمان",
      country_enNationality: "Solomon Island",
      country_arNationality: "جزر سليمان",
    },
    {
      id: "3b7bb73b-ecc1-4f00-ab5f-3e9794a8fb5b",
      country_code: "AF",
      country_enName: "Afghanistan",
      country_arName: "أفغانستان",
      country_enNationality: "Afghan",
      country_arNationality: "أفغانستاني",
    },
    {
      id: "8f150a58-4bba-4e56-9bae-3f26ca53947a",
      country_code: "MV",
      country_enName: "Maldives",
      country_arName: "المالديف",
      country_enNationality: "Maldivian",
      country_arNationality: "مالديفي",
    },
    {
      id: "f994ce7e-d1fc-43b0-ba55-402f5060c159",
      country_code: "SC",
      country_enName: "Seychelles",
      country_arName: "سيشيل",
      country_enNationality: "Seychellois",
      country_arNationality: "سيشيلي",
    },
    {
      id: "600eee81-fb68-47a8-9328-40e7e6e7e429",
      country_code: "MA",
      country_enName: "Morocco",
      country_arName: "المغرب",
      country_enNationality: "Moroccan",
      country_arNationality: "مغربي",
    },
    {
      id: "c1cf048a-4e78-4041-aa23-41f09a7b8cce",
      country_code: "DM",
      country_enName: "Dominica",
      country_arName: "دومينيكا",
      country_enNationality: "Dominican",
      country_arNationality: "دومينيكي",
    },
    {
      id: "62ea0371-66ca-4d6f-ac96-41f2cd556401",
      country_code: "MC",
      country_enName: "Monaco",
      country_arName: "موناكو",
      country_enNationality: "Monacan",
      country_arNationality: "مونيكي",
    },
    {
      id: "a6bb7c77-8288-4a9c-bf65-44e4b8d3f37a",
      country_code: "HR",
      country_enName: "Croatia",
      country_arName: "كرواتيا",
      country_enNationality: "Croatian",
      country_arNationality: "كوراتي",
    },
    {
      id: "219bf727-f797-49f6-9b2c-4626f886a378",
      country_code: "NG",
      country_enName: "Nigeria",
      country_arName: "نيجيريا",
      country_enNationality: "Nigerian",
      country_arNationality: "نيجيري",
    },
    {
      id: "8c96c966-dcaa-4411-afd7-47861af224bb",
      country_code: "GY",
      country_enName: "Guyana",
      country_arName: "غيانا",
      country_enNationality: "Guyanese",
      country_arNationality: "غياني",
    },
    {
      id: "721275b4-c808-44a5-b78a-49ce02679446",
      country_code: "ET",
      country_enName: "Ethiopia",
      country_arName: "أثيوبيا",
      country_enNationality: "Ethiopian",
      country_arNationality: "أثيوبي",
    },
    {
      id: "175e1987-2bee-4659-b574-4b07401163c7",
      country_code: "MO",
      country_enName: "Macau",
      country_arName: "ماكاو",
      country_enNationality: "Macanese",
      country_arNationality: "ماكاوي",
    },
    {
      id: "8b883231-3d95-40e5-8bff-4b1772f3ac7c",
      country_code: "TV",
      country_enName: "Tuvalu",
      country_arName: "توفالو",
      country_enNationality: "Tuvaluan",
      country_arNationality: "توفالي",
    },
    {
      id: "b4949713-12ad-4c86-8990-4b64a9be8199",
      country_code: "MH",
      country_enName: "Marshall Islands",
      country_arName: "جزر مارشال",
      country_enNationality: "Marshallese",
      country_arNationality: "مارشالي",
    },
    {
      id: "b57f2cbc-f19b-4ced-9637-4b8e1c4bc4a5",
      country_code: "KP",
      country_enName: "Korea(North Korea)",
      country_arName: "كوريا الشمالية",
      country_enNationality: "North Korean",
      country_arNationality: "كوري",
    },
    {
      id: "e9147a20-1271-47a7-8eec-4ca8c9f479d5",
      country_code: "KY",
      country_enName: "Cayman Islands",
      country_arName: "جزر كايمان",
      country_enNationality: "Caymanian",
      country_arNationality: "كايماني",
    },
    {
      id: "0e4b61d5-0c21-4722-b623-4e1108296b81",
      country_code: "NP",
      country_enName: "Nepal",
      country_arName: "نيبال",
      country_enNationality: "Nepalese",
      country_arNationality: "نيبالي",
    },
    {
      id: "593268fd-d2a7-4057-b297-4eed3cc94ceb",
      country_code: "ZM",
      country_enName: "Zambia",
      country_arName: "زامبيا",
      country_enNationality: "Zambian",
      country_arNationality: "زامبياني",
    },
    {
      id: "6a441cda-638f-4d2e-b99d-522eae53b931",
      country_code: "AM",
      country_enName: "Armenia",
      country_arName: "أرمينيا",
      country_enNationality: "Armenian",
      country_arNationality: "أرميني",
    },
    {
      id: "b19ab3e8-09b7-421a-8f38-5267c2c7f194",
      country_code: "OM",
      country_enName: "Oman",
      country_arName: "عمان",
      country_enNationality: "Omani",
      country_arNationality: "عماني",
    },
    {
      id: "081bb34d-ca4a-4c3e-bf34-530462f42bde",
      country_code: "RW",
      country_enName: "Rwanda",
      country_arName: "رواندا",
      country_enNationality: "Rwandan",
      country_arNationality: "رواندا",
    },
    {
      id: "0f97417e-9a75-4b03-9bb6-5388db555ec2",
      country_code: "DZ",
      country_enName: "Algeria",
      country_arName: "الجزائر",
      country_enNationality: "Algerian",
      country_arNationality: "جزائري",
    },
    {
      id: "0aef6879-6c44-456b-a99d-546f8535c727",
      country_code: "CZ",
      country_enName: "Czech Republic",
      country_arName: "الجمهورية التشيكية",
      country_enNationality: "Czech",
      country_arNationality: "تشيكي",
    },
    {
      id: "3c7cbb74-cdbd-4fe2-8693-54e59e7a29f7",
      country_code: "GS",
      country_enName: "South Georgia and the South Sandwich",
      country_arName: "المنطقة القطبية الجنوبية",
      country_enNationality: "South Georgia and the South Sandwich",
      country_arNationality: "لمنطقة القطبية الجنوبية",
    },
    {
      id: "de1ad157-7487-4a49-9887-55684bbf6c7c",
      country_code: "CY",
      country_enName: "Cyprus",
      country_arName: "قبرص",
      country_enNationality: "Cypriot",
      country_arNationality: "قبرصي",
    },
    {
      id: "ee698ec9-809c-400b-8c5f-556e1fb42e62",
      country_code: "GL",
      country_enName: "Greenland",
      country_arName: "جرينلاند",
      country_enNationality: "Greenlandic",
      country_arNationality: "جرينلاندي",
    },
    {
      id: "0c8d9958-eb78-4702-ad6d-55b923587e8c",
      country_code: "MX",
      country_enName: "Mexico",
      country_arName: "المكسيك",
      country_enNationality: "Mexican",
      country_arNationality: "مكسيكي",
    },
    {
      id: "8a138ce7-cbd7-4399-a193-56e39ef070a9",
      country_code: "AS",
      country_enName: "American Samoa",
      country_arName: "ساموا-الأمريكي",
      country_enNationality: "American Samoan",
      country_arNationality: "أمريكي سامواني",
    },
    {
      id: "8f842ad8-8839-4de1-b15f-5807875fe0cc",
      country_code: "CF",
      country_enName: "Central African Republic",
      country_arName: "جمهورية أفريقيا الوسطى",
      country_enNationality: "Central African",
      country_arNationality: "أفريقي",
    },
    {
      id: "6fb9a5ca-b2c5-4d29-91da-58340204176f",
      country_code: "AT",
      country_enName: "Austria",
      country_arName: "النمسا",
      country_enNationality: "Austrian",
      country_arNationality: "نمساوي",
    },
    {
      id: "53b3903f-19d4-4ac7-872f-59ad4b41027d",
      country_code: "BE",
      country_enName: "Belgium",
      country_arName: "بلجيكا",
      country_enNationality: "Belgian",
      country_arNationality: "بلجيكي",
    },
    {
      id: "1a56402d-6c01-418e-8c77-5a781339325b",
      country_code: "SX",
      country_enName: "Sint Maarten (Dutch part)",
      country_arName: "ساينت مارتن هولندي",
      country_enNationality: "St. Martian(Dutch)",
      country_arNationality: "ساينت مارتني هولندي",
    },
    {
      id: "0f1ca2c3-32c7-4816-b330-5aab6eeaff55",
      country_code: "PK",
      country_enName: "Pakistan",
      country_arName: "باكستان",
      country_enNationality: "Pakistani",
      country_arNationality: "باكستاني",
    },
    {
      id: "4577dfe8-ddf6-4f97-96ff-5c16c6472358",
      country_code: "BM",
      country_enName: "Bermuda",
      country_arName: "جزر برمودا",
      country_enNationality: "Bermudan",
      country_arNationality: "برمودي",
    },
    {
      id: "bbff5d34-c4c3-45fa-bceb-5c312ecf4f80",
      country_code: "LT",
      country_enName: "Lithuania",
      country_arName: "لتوانيا",
      country_enNationality: "Lithuanian",
      country_arNationality: "لتوانيي",
    },
    {
      id: "2b826de7-d9fb-4eae-9acb-605c6c124e3d",
      country_code: "BS",
      country_enName: "Bahamas",
      country_arName: "الباهاماس",
      country_enNationality: "Bahamian",
      country_arNationality: "باهاميسي",
    },
    {
      id: "a2675e08-93f5-41fd-9e4c-6552f1ebef17",
      country_code: "MM",
      country_enName: "Myanmar",
      country_arName: "ميانمار",
      country_enNationality: "Myanmarian",
      country_arNationality: "ميانماري",
    },
    {
      id: "ed8a7a33-4936-4773-ba64-656355a81267",
      country_code: "KM",
      country_enName: "Comoros",
      country_arName: "جزر القمر",
      country_enNationality: "Comorian",
      country_arNationality: "جزر القمر",
    },
    {
      id: "603f545d-77b9-4af7-8c15-673a757568d2",
      country_code: "GU",
      country_enName: "Guam",
      country_arName: "جوام",
      country_enNationality: "Guamanian",
      country_arNationality: "جوامي",
    },
    {
      id: "eb047d3d-71b0-4dfa-b4ae-676026c680a0",
      country_code: "SI",
      country_enName: "Slovenia",
      country_arName: "سلوفينيا",
      country_enNationality: "Slovenian",
      country_arNationality: "سولفيني",
    },
    {
      id: "8f74046b-cfc3-4ddd-899a-6785e0f2dc8c",
      country_code: "PL",
      country_enName: "Poland",
      country_arName: "بولندا",
      country_enNationality: "Polish",
      country_arNationality: "بولندي",
    },
    {
      id: "4c2e7025-d8bc-46f3-b71b-67b4ee355f1f",
      country_code: "SK",
      country_enName: "Slovakia",
      country_arName: "سلوفاكيا",
      country_enNationality: "Slovak",
      country_arNationality: "سولفاكي",
    },
    {
      id: "7a051a10-3f52-45d7-a309-6862c545b41c",
      country_code: "CL",
      country_enName: "Chile",
      country_arName: "شيلي",
      country_enNationality: "Chilean",
      country_arNationality: "شيلي",
    },
    {
      id: "9a47c31a-9785-4982-9854-6a5fae1a3f79",
      country_code: "KN",
      country_enName: "Saint Kitts and Nevis",
      country_arName: "سانت كيتس ونيفس,",
      country_enNationality: "Kittitian/Nevisian",
      country_arNationality: "سانت كيتس ونيفس",
    },
    {
      id: "0d7b9e04-1310-46ef-8018-6a7955451416",
      country_code: "PF",
      country_enName: "French Polynesia",
      country_arName: "بولينيزيا الفرنسية",
      country_enNationality: "French Polynesian",
      country_arNationality: "بولينيزيي",
    },
    {
      id: "1173b73a-822f-474d-a464-6b4dea0e0c88",
      country_code: "KE",
      country_enName: "Kenya",
      country_arName: "كينيا",
      country_enNationality: "Kenyan",
      country_arNationality: "كيني",
    },
    {
      id: "a3dffe58-a441-448c-841f-6bfc0b51fe4b",
      country_code: "SY",
      country_enName: "Syria",
      country_arName: "سوريا",
      country_enNationality: "Syrian",
      country_arNationality: "سوري",
    },
    {
      id: "4c38e3cd-27c0-47f4-b3a3-6c3a22b679da",
      country_code: "BA",
      country_enName: "Bosnia and Herzegovina",
      country_arName: "البوسنة و الهرسك",
      country_enNationality: "Bosnian / Herzegovinian",
      country_arNationality: "بوسني/هرسكي",
    },
    {
      id: "490b92bf-c68d-4475-bbc4-6c4cc40821fc",
      country_code: "HU",
      country_enName: "Hungary",
      country_arName: "المجر",
      country_enNationality: "Hungarian",
      country_arNationality: "مجري",
    },
    {
      id: "49fd80b6-98f3-4d17-bac5-6c5c43cd755a",
      country_code: "CV",
      country_enName: "Cape Verde",
      country_arName: "الرأس الأخضر",
      country_enNationality: "Cape Verdean",
      country_arNationality: "الرأس الأخضر",
    },
    {
      id: "3f5115bc-8c8a-45cd-a1f0-6c92aa4b4dbe",
      country_code: "CG",
      country_enName: "Congo",
      country_arName: "الكونغو",
      country_enNationality: "Congolese",
      country_arNationality: "كونغي",
    },
    {
      id: "d92a09d4-1dc5-46b8-9ed5-6dfdf2d5fed6",
      country_code: "BV",
      country_enName: "Bouvet Island",
      country_arName: "جزيرة بوفيه",
      country_enNationality: "Bouvetian",
      country_arNationality: "بوفيهي",
    },
    {
      id: "4300baaa-4d23-495f-8612-7050407ac5e0",
      country_code: "TG",
      country_enName: "Togo",
      country_arName: "توغو",
      country_enNationality: "Togolese",
      country_arNationality: "توغي",
    },
    {
      id: "de2573cf-61ce-4756-8493-721359da3a78",
      country_code: "PS",
      country_enName: "Palestine",
      country_arName: "فلسطين",
      country_enNationality: "Palestinian",
      country_arNationality: "فلسطيني",
    },
    {
      id: "fa730d0c-2e59-4672-a6a4-74031326c21d",
      country_code: "GH",
      country_enName: "Ghana",
      country_arName: "غانا",
      country_enNationality: "Ghanaian",
      country_arNationality: "غاني",
    },
    {
      id: "6a4a0253-680d-4e6a-b9b6-75f2c0d819b0",
      country_code: "HK",
      country_enName: "Hong Kong",
      country_arName: "هونغ كونغ",
      country_enNationality: "Hongkongese",
      country_arNationality: "هونغ كونغي",
    },
    {
      id: "5db5b120-7342-4ef7-b924-76a6510f3863",
      country_code: "TR",
      country_enName: "Turkey",
      country_arName: "تركيا",
      country_enNationality: "Turkish",
      country_arNationality: "تركي",
    },
    {
      id: "2e8a258f-b514-456d-a1cb-77020cfbcafe",
      country_code: "EE",
      country_enName: "Estonia",
      country_arName: "استونيا",
      country_enNationality: "Estonian",
      country_arNationality: "استوني",
    },
    {
      id: "a6337b2f-f5b6-43bd-8dfe-7842dd6a5818",
      country_code: "BT",
      country_enName: "Bhutan",
      country_arName: "بوتان",
      country_enNationality: "Bhutanese",
      country_arNationality: "بوتاني",
    },
    {
      id: "a001d410-0fcb-4888-86d4-787c1c22b568",
      country_code: "ZW",
      country_enName: "Zimbabwe",
      country_arName: "زمبابوي",
      country_enNationality: "Zimbabwean",
      country_arNationality: "زمبابوي",
    },
    {
      id: "0ab6f769-ff4f-4ae2-ac6e-791c01378bb7",
      country_code: "AZ",
      country_enName: "Azerbaijan",
      country_arName: "أذربيجان",
      country_enNationality: "Azerbaijani",
      country_arNationality: "أذربيجاني",
    },
    {
      id: "a01fbdec-6f52-410b-b1c0-794568124b30",
      country_code: "UA",
      country_enName: "Ukraine",
      country_arName: "أوكرانيا",
      country_enNationality: "Ukrainian",
      country_arNationality: "أوكراني",
    },
    {
      id: "c54ebce8-5c0a-4433-a526-795716da7e87",
      country_code: "BW",
      country_enName: "Botswana",
      country_arName: "بوتسوانا",
      country_enNationality: "Botswanan",
      country_arNationality: "بوتسواني",
    },
    {
      id: "d1da0b5d-6689-4c18-9b77-7a5fe7a78fed",
      country_code: "NI",
      country_enName: "Nicaragua",
      country_arName: "نيكاراجوا",
      country_enNationality: "Nicaraguan",
      country_arNationality: "نيكاراجوي",
    },
    {
      id: "62b3fe54-c564-4e26-ba40-7b064bce772f",
      country_code: "EG",
      country_enName: "Egypt",
      country_arName: "مصر",
      country_enNationality: "Egyptian",
      country_arNationality: "مصري",
    },
    {
      id: "32283571-9eb6-4147-a892-7b455a49c4f1",
      country_code: "MS",
      country_enName: "Montserrat",
      country_arName: "مونتسيرات",
      country_enNationality: "Montserratian",
      country_arNationality: "مونتسيراتي",
    },
    {
      id: "54c33adc-247e-47a6-8793-7b759b205238",
      country_code: "KR",
      country_enName: "Korea(South Korea)",
      country_arName: "كوريا الجنوبية",
      country_enNationality: "South Korean",
      country_arNationality: "كوري",
    },
    {
      id: "637539f3-f2dc-414b-a881-81a49f6feccf",
      country_code: "BG",
      country_enName: "Bulgaria",
      country_arName: "بلغاريا",
      country_enNationality: "Bulgarian",
      country_arNationality: "بلغاري",
    },
    {
      id: "425c9c86-3987-4292-bfb9-8209c77142f9",
      country_code: "SH",
      country_enName: "Saint Helena",
      country_arName: "سانت هيلانة",
      country_enNationality: "St. Helenian",
      country_arNationality: "هيلاني",
    },
    {
      id: "3d55a5c9-f2d2-45d2-9276-82c22dde6f17",
      country_code: "BJ",
      country_enName: "Benin",
      country_arName: "بنين",
      country_enNationality: "Beninese",
      country_arNationality: "بنيني",
    },
    {
      id: "3681f1f0-4ab2-44df-a064-83ef32596332",
      country_code: "LY",
      country_enName: "Libya",
      country_arName: "ليبيا",
      country_enNationality: "Libyan",
      country_arNationality: "ليبي",
    },
    {
      id: "1d6fed3b-f970-4dc0-b245-862d269a6cf9",
      country_code: "BO",
      country_enName: "Bolivia",
      country_arName: "بوليفيا",
      country_enNationality: "Bolivian",
      country_arNationality: "بوليفي",
    },
    {
      id: "1cfadaba-0f4d-4803-8511-870d961b2a84",
      country_code: "NE",
      country_enName: "Niger",
      country_arName: "النيجر",
      country_enNationality: "Nigerien",
      country_arNationality: "نيجيري",
    },
    {
      id: "c885e6c3-cfb6-471e-9366-873f6ba1f43e",
      country_code: "SJ",
      country_enName: "Svalbard and Jan Mayen",
      country_arName: "سفالبارد ويان ماين",
      country_enNationality: "Svalbardian/Jan Mayenian",
      country_arNationality: "سفالبارد ويان ماين",
    },
    {
      id: "b9678dc1-c027-4495-9982-8747e06e3ba7",
      country_code: "JP",
      country_enName: "Japan",
      country_arName: "اليابان",
      country_enNationality: "Japanese",
      country_arNationality: "ياباني",
    },
    {
      id: "e0dc2072-3651-44a6-8073-8a863a3d37cf",
      country_code: "AI",
      country_enName: "Anguilla",
      country_arName: "أنغويلا",
      country_enNationality: "Anguillan",
      country_arNationality: "أنغويلي",
    },
    {
      id: "62962168-5642-4470-9d2c-8b325da88a14",
      country_code: "UG",
      country_enName: "Uganda",
      country_arName: "أوغندا",
      country_enNationality: "Ugandan",
      country_arNationality: "أوغندي",
    },
    {
      id: "9b7646e0-8466-45c5-8bfa-8c2841b8cafb",
      country_code: "NU",
      country_enName: "Niue",
      country_arName: "ني",
      country_enNationality: "Niuean",
      country_arNationality: "ني",
    },
    {
      id: "e505be25-8527-46b5-bb60-8d24496c2f8a",
      country_code: "TT",
      country_enName: "Trinidad and Tobago",
      country_arName: "ترينيداد وتوباغو",
      country_enNationality: "Trinidadian/Tobagonian",
      country_arNationality: "ترينيداد وتوباغو",
    },
    {
      id: "0593ada7-362f-4b5d-b45c-8e9c7980009d",
      country_code: "LB",
      country_enName: "Lebanon",
      country_arName: "لبنان",
      country_enNationality: "Lebanese",
      country_arNationality: "لبناني",
    },
    {
      id: "a5e4448c-5818-4ed1-9f76-8e9ea98e9865",
      country_code: "GE",
      country_enName: "Georgia",
      country_arName: "جيورجيا",
      country_enNationality: "Georgian",
      country_arNationality: "جيورجي",
    },
    {
      id: "a760b65f-a7b0-47fb-9528-8ea687832fa4",
      country_code: "BR",
      country_enName: "Brazil",
      country_arName: "البرازيل",
      country_enNationality: "Brazilian",
      country_arNationality: "برازيلي",
    },
    {
      id: "03bfc700-7312-4de5-89e2-8f25ccd5dab2",
      country_code: "ML",
      country_enName: "Mali",
      country_arName: "مالي",
      country_enNationality: "Malian",
      country_arNationality: "مالي",
    },
    {
      id: "6d51e089-0a9d-49e1-86d6-8f2bdc678da8",
      country_code: "SZ",
      country_enName: "Swaziland",
      country_arName: "سوازيلند",
      country_enNationality: "Swazi",
      country_arNationality: "سوازيلندي",
    },
    {
      id: "45ef23cf-4e3e-4f1e-aa14-8f76659408ed",
      country_code: "BZ",
      country_enName: "Belize",
      country_arName: "بيليز",
      country_enNationality: "Belizean",
      country_arNationality: "بيليزي",
    },
    {
      id: "61db0d58-c904-468f-81c4-902aa4cf1d48",
      country_code: "YE",
      country_enName: "Yemen",
      country_arName: "اليمن",
      country_enNationality: "Yemeni",
      country_arNationality: "يمني",
    },
    {
      id: "8705d047-da7c-47a0-acf4-90782d04d19a",
      country_code: "ES",
      country_enName: "Spain",
      country_arName: "إسبانيا",
      country_enNationality: "Spanish",
      country_arNationality: "إسباني",
    },
    {
      id: "262b5959-d30b-4343-ad13-9106627ceaf7",
      country_code: "SM",
      country_enName: "San Marino",
      country_arName: "سان مارينو",
      country_enNationality: "Sammarinese",
      country_arNationality: "ماريني",
    },
    {
      id: "2a046469-4af6-43b2-93bf-92f87a19d2a2",
      country_code: "DK",
      country_enName: "Denmark",
      country_arName: "الدانمارك",
      country_enNationality: "Danish",
      country_arNationality: "دنماركي",
    },
    {
      id: "c1b92bc5-b803-4c1b-9656-9373c39a3a31",
      country_code: "SD",
      country_enName: "Sudan",
      country_arName: "السودان",
      country_enNationality: "Sudanese",
      country_arNationality: "سوداني",
    },
    {
      id: "a583f8c5-15b4-478b-bb4e-940515f26bca",
      country_code: "XK",
      country_enName: "Kosovo",
      country_arName: "كوسوفو",
      country_enNationality: "Kosovar",
      country_arNationality: "كوسيفي",
    },
    {
      id: "a3ee179d-524e-4f10-9903-9462f10312f9",
      country_code: "BH",
      country_enName: "Bahrain",
      country_arName: "البحرين",
      country_enNationality: "Bahraini",
      country_arNationality: "بحريني",
    },
    {
      id: "548e44dd-5617-42de-ba75-98647bc6119c",
      country_code: "MT",
      country_enName: "Malta",
      country_arName: "مالطا",
      country_enNationality: "Maltese",
      country_arNationality: "مالطي",
    },
    {
      id: "4270a5b9-f959-4862-91d9-9a14fab10dea",
      country_code: "IO",
      country_enName: "British Indian Ocean Territory",
      country_arName: "إقليم المحيط الهندي البريطاني",
      country_enNationality: "British Indian Ocean Territory",
      country_arNationality: "إقليم المحيط الهندي البريطاني",
    },
    {
      id: "f7ffbdc4-b85c-4b33-8d11-9a19fdea977f",
      country_code: "BF",
      country_enName: "Burkina Faso",
      country_arName: "بوركينا فاسو",
      country_enNationality: "Burkinabe",
      country_arNationality: "بوركيني",
    },
    {
      id: "912899e0-2eba-404b-a504-9e03b76bfabf",
      country_code: "MY",
      country_enName: "Malaysia",
      country_arName: "ماليزيا",
      country_enNationality: "Malaysian",
      country_arNationality: "ماليزي",
    },
    {
      id: "a8a0d96c-7629-44b9-9455-9e258ac0f5f9",
      country_code: "ER",
      country_enName: "Eritrea",
      country_arName: "إريتريا",
      country_enNationality: "Eritrean",
      country_arNationality: "إريتيري",
    },
    {
      id: "7c2fb290-79b5-4321-b2ee-a026a5ac5586",
      country_code: "GT",
      country_enName: "Guatemala",
      country_arName: "غواتيمال",
      country_enNationality: "Guatemalan",
      country_arNationality: "غواتيمالي",
    },
    {
      id: "b27d7c2b-478c-4d2c-8f02-a043d4bd7629",
      country_code: "CX",
      country_enName: "Christmas Island",
      country_arName: "جزيرة عيد الميلاد",
      country_enNationality: "Christmas Islander",
      country_arNationality: "جزيرة عيد الميلاد",
    },
    {
      id: "03f12c4b-0c76-4ff5-8935-a0459a0aca02",
      country_code: "MN",
      country_enName: "Mongolia",
      country_arName: "منغوليا",
      country_enNationality: "Mongolian",
      country_arNationality: "منغولي",
    },
    {
      id: "fb008ec6-576a-416d-a0ab-a305d82f6c96",
      country_code: "CA",
      country_enName: "Canada",
      country_arName: "كندا",
      country_enNationality: "Canadian",
      country_arNationality: "كندي",
    },
    {
      id: "f51f6ac8-8915-4788-b89d-a43f485569e5",
      country_code: "NL",
      country_enName: "Netherlands",
      country_arName: "هولندا",
      country_enNationality: "Dutch",
      country_arNationality: "هولندي",
    },
    {
      id: "22bf03fc-2f75-4407-a222-a5887d8a114a",
      country_code: "DJ",
      country_enName: "Djibouti",
      country_arName: "جيبوتي",
      country_enNationality: "Djiboutian",
      country_arNationality: "جيبوتي",
    },
    {
      id: "7e080179-6226-4555-8c53-a7cabbc98e27",
      country_code: "PE",
      country_enName: "Peru",
      country_arName: "بيرو",
      country_enNationality: "Peruvian",
      country_arNationality: "بيري",
    },
    {
      id: "614931cd-ca5c-4534-9ca3-a8ab7626de6f",
      country_code: "CM",
      country_enName: "Cameroon",
      country_arName: "كاميرون",
      country_enNationality: "Cameroonian",
      country_arNationality: "كاميروني",
    },
    {
      id: "312b35ad-adef-4437-9956-a9841a883a5e",
      country_code: "GI",
      country_enName: "Gibraltar",
      country_arName: "جبل طارق",
      country_enNationality: "Gibraltar",
      country_arNationality: "جبل طارق",
    },
    {
      id: "1d6a1541-fda3-46b3-978f-ad8c846ebb02",
      country_code: "CO",
      country_enName: "Colombia",
      country_arName: "كولومبيا",
      country_enNationality: "Colombian",
      country_arNationality: "كولومبي",
    },
    {
      id: "805f9da6-b9eb-47fb-af1f-ae09fff85407",
      country_code: "TL",
      country_enName: "Timor-Leste",
      country_arName: "تيمور الشرقية",
      country_enNationality: "Timor-Lestian",
      country_arNationality: "تيموري",
    },
    {
      id: "ee749c74-cbf0-416d-9607-ae534f178fa5",
      country_code: "AX",
      country_enName: "Aland Islands",
      country_arName: "جزر آلاند",
      country_enNationality: "Aland Islander",
      country_arNationality: "آلاندي",
    },
    {
      id: "d0ed0cad-68e9-407c-a103-aeadb98bed06",
      country_code: "GR",
      country_enName: "Greece",
      country_arName: "اليونان",
      country_enNationality: "Greek",
      country_arNationality: "يوناني",
    },
    {
      id: "d050c709-1cec-43ce-847d-af9903b327c5",
      country_code: "RU",
      country_enName: "Russian",
      country_arName: "روسيا",
      country_enNationality: "Russian",
      country_arNationality: "روسي",
    },
    {
      id: "5672a9b8-c60a-481d-9395-b022ea641c89",
      country_code: "GP",
      country_enName: "Guadeloupe",
      country_arName: "جزر جوادلوب",
      country_enNationality: "Guadeloupe",
      country_arNationality: "جزر جوادلوب",
    },
    {
      id: "daf6954f-48e3-40f5-b9e6-b18cccad4a97",
      country_code: "TO",
      country_enName: "Tonga",
      country_arName: "تونغا",
      country_enNationality: "Tongan",
      country_arNationality: "تونغي",
    },
    {
      id: "0e6dd9bc-942d-41ba-92da-b1f39c68bc1e",
      country_code: "BL",
      country_enName: "Saint Barthelemy",
      country_arName: "سان بارتيلمي",
      country_enNationality: "Saint Barthelmian",
      country_arNationality: "سان بارتيلمي",
    },
    {
      id: "67a90a7c-e29b-4ea8-9aca-b41c58130bc6",
      country_code: "SR",
      country_enName: "Suriname",
      country_arName: "سورينام",
      country_enNationality: "Surinamese",
      country_arNationality: "سورينامي",
    },
    {
      id: "eefd718b-69f3-433d-a614-b473154e9dbe",
      country_code: "DE",
      country_enName: "Germany",
      country_arName: "ألمانيا",
      country_enNationality: "German",
      country_arNationality: "ألماني",
    },
    {
      id: "42740cf3-85de-4d6c-8609-b581acfdfbac",
      country_code: "NR",
      country_enName: "Nauru",
      country_arName: "نورو",
      country_enNationality: "Nauruan",
      country_arNationality: "نوري",
    },
    {
      id: "735f2a13-f597-4e73-bd31-b6f10ef9a0d8",
      country_code: "TJ",
      country_enName: "Tajikistan",
      country_arName: "طاجيكستان",
      country_enNationality: "Tajikistani",
      country_arNationality: "طاجيكستاني",
    },
    {
      id: "3097c65d-14ee-4707-beb2-b77ad36c2888",
      country_code: "ZA",
      country_enName: "South Africa",
      country_arName: "جنوب أفريقيا",
      country_enNationality: "South African",
      country_arNationality: "أفريقي",
    },
    {
      id: "b5e319cd-9a25-4f56-8140-b858e3bac3e0",
      country_code: "VE",
      country_enName: "Venezuela",
      country_arName: "فنزويلا",
      country_enNationality: "Venezuelan",
      country_arNationality: "فنزويلي",
    },
    {
      id: "361c2563-e816-4c5d-919d-b92294cd721a",
      country_code: "ID",
      country_enName: "Indonesia",
      country_arName: "أندونيسيا",
      country_enNationality: "Indonesian",
      country_arNationality: "أندونيسيي",
    },
    {
      id: "5d5754ac-79ed-4a42-b9bc-bce1357036a1",
      country_code: "PW",
      country_enName: "Palau",
      country_arName: "بالاو",
      country_enNationality: "Palauan",
      country_arNationality: "بالاوي",
    },
    {
      id: "b39a6550-cb61-4267-a7d4-bd566bba8501",
      country_code: "IL",
      country_enName: "Israel",
      country_arName: "إسرائيل",
      country_enNationality: "Israeli",
      country_arNationality: "إسرائيلي",
    },
    {
      id: "2441443b-9d47-49ef-8b27-bd8fa7b7a3b2",
      country_code: "AG",
      country_enName: "Antigua and Barbuda",
      country_arName: "أنتيغوا وبربودا",
      country_enNationality: "Antiguan",
      country_arNationality: "بربودي",
    },
    {
      id: "9ad317f5-31d4-4df7-9d7b-be8c99483716",
      country_code: "BB",
      country_enName: "Barbados",
      country_arName: "بربادوس",
      country_enNationality: "Barbadian",
      country_arNationality: "بربادوسي",
    },
    {
      id: "d7254079-9132-44c3-9cdf-bf60d376f871",
      country_code: "SV",
      country_enName: "El Salvador",
      country_arName: "إلسلفادور",
      country_enNationality: "Salvadoran",
      country_arNationality: "سلفادوري",
    },
    {
      id: "8a1077c7-fbb5-4908-b819-bf9eb2f9164c",
      country_code: "AU",
      country_enName: "Australia",
      country_arName: "أستراليا",
      country_enNationality: "Australian",
      country_arNationality: "أسترالي",
    },
    {
      id: "0bb5d489-29c6-4a6a-b391-bfb5623bab43",
      country_code: "LK",
      country_enName: "Sri Lanka",
      country_arName: "سريلانكا",
      country_enNationality: "Sri Lankian",
      country_arNationality: "سريلانكي",
    },
    {
      id: "1e5b9c36-eef5-45a4-a858-c198ba01c971",
      country_code: "AQ",
      country_enName: "Antarctica",
      country_arName: "أنتاركتيكا",
      country_enNationality: "Antarctican",
      country_arNationality: "أنتاركتيكي",
    },
    {
      id: "6d8f204a-7680-4ce8-9a58-c27f7df40e97",
      country_code: "LS",
      country_enName: "Lesotho",
      country_arName: "ليسوتو",
      country_enNationality: "Basotho",
      country_arNationality: "ليوسيتي",
    },
    {
      id: "42e1e659-7c0f-4d88-ab57-c37549938611",
      country_code: "QA",
      country_enName: "Qatar",
      country_arName: "قطر",
      country_enNationality: "Qatari",
      country_arNationality: "قطري",
    },
    {
      id: "caebac1b-41ae-4576-83ea-c4c25db43fef",
      country_code: "GD",
      country_enName: "Grenada",
      country_arName: "غرينادا",
      country_enNationality: "Grenadian",
      country_arNationality: "غرينادي",
    },
    {
      id: "0b4104b9-dbec-467a-9e79-c569000c8522",
      country_code: "MK",
      country_enName: "Macedonia",
      country_arName: "مقدونيا",
      country_enNationality: "Macedonian",
      country_arNationality: "مقدوني",
    },
    {
      id: "c9783f04-f1f3-4cbd-9fc0-c56e22929304",
      country_code: "BI",
      country_enName: "Burundi",
      country_arName: "بوروندي",
      country_enNationality: "Burundian",
      country_arNationality: "بورونيدي",
    },
    {
      id: "7073d523-baf9-490a-8b3d-c6e7dc420152",
      country_code: "BY",
      country_enName: "Belarus",
      country_arName: "روسيا البيضاء",
      country_enNationality: "Belarusian",
      country_arNationality: "روسي",
    },
    {
      id: "e2578030-a8ff-4c04-94f7-c7f497dc500d",
      country_code: "CI",
      country_enName: "Ivory Coast",
      country_arName: "ساحل العاج",
      country_enNationality: "Ivory Coastian",
      country_arNationality: "ساحل العاج",
    },
    {
      id: "d5c055ad-3171-4422-8d1e-c8e37529844a",
      country_code: "DO",
      country_enName: "Dominican Republic",
      country_arName: "الجمهورية الدومينيكية",
      country_enNationality: "Dominican",
      country_arNationality: "دومينيكي",
    },
    {
      id: "76284b65-0645-403f-a4c9-c9caf40b0905",
      country_code: "GQ",
      country_enName: "Equatorial Guinea",
      country_arName: "غينيا الاستوائي",
      country_enNationality: "Equatorial Guinean",
      country_arNationality: "غيني",
    },
    {
      id: "bc81f12b-b720-4ade-8189-c9dc378dd513",
      country_code: "AN",
      country_enName: "Netherlands Antilles",
      country_arName: "جزر الأنتيل الهولندي",
      country_enNationality: "Dutch Antilier",
      country_arNationality: "هولندي",
    },
    {
      id: "c7261c49-2b97-4540-ab06-ca4145f91f16",
      country_code: "SN",
      country_enName: "Senegal",
      country_arName: "السنغال",
      country_enNationality: "Senegalese",
      country_arNationality: "سنغالي",
    },
    {
      id: "cef20818-3004-4b8c-96f6-cbad573a641d",
      country_code: "LU",
      country_enName: "Luxembourg",
      country_arName: "لوكسمبورغ",
      country_enNationality: "Luxembourger",
      country_arNationality: "لوكسمبورغي",
    },
    {
      id: "61af7343-7557-4c56-8a8e-cbd25946fc5c",
      country_code: "AD",
      country_enName: "Andorra",
      country_arName: "أندورا",
      country_enNationality: "Andorran",
      country_arNationality: "أندوري",
    },
    {
      id: "2b6a042f-ff8d-4711-ad91-cc44e23b09af",
      country_code: "HM",
      country_enName: "Heard and Mc Donald Islands",
      country_arName: "جزيرة هيرد وجزر ماكدونالد",
      country_enNationality: "Heard and Mc Donald Islanders",
      country_arNationality: "جزيرة هيرد وجزر ماكدونالد",
    },
    {
      id: "2cb62f52-0df5-4c40-85b4-ccccacea2715",
      country_code: "LR",
      country_enName: "Liberia",
      country_arName: "ليبيريا",
      country_enNationality: "Liberian",
      country_arNationality: "ليبيري",
    },
    {
      id: "35b9d727-ae29-451c-b272-cfd15a7c7997",
      country_code: "GG",
      country_enName: "Guernsey",
      country_arName: "غيرنزي",
      country_enNationality: "Guernsian",
      country_arNationality: "غيرنزي",
    },
    {
      id: "a36d13cd-9bee-4518-80f4-cfdd9d5e94d2",
      country_code: "VN",
      country_enName: "Vietnam",
      country_arName: "فيتنام",
      country_enNationality: "Vietnamese",
      country_arNationality: "فيتنامي",
    },
    {
      id: "13b1af36-5160-451d-b6df-d213d392cec4",
      country_code: "FJ",
      country_enName: "Fiji",
      country_arName: "فيجي",
      country_enNationality: "Fijian",
      country_arNationality: "فيجي",
    },
    {
      id: "05e6e1e4-b31c-4f7a-b8ad-d25c7bac6940",
      country_code: "MW",
      country_enName: "Malawi",
      country_arName: "مالاوي",
      country_enNationality: "Malawian",
      country_arNationality: "مالاوي",
    },
    {
      id: "17f1d559-51d0-4472-91b5-d28e62795ab1",
      country_code: "UY",
      country_enName: "Uruguay",
      country_arName: "أورغواي",
      country_enNationality: "Uruguayan",
      country_arNationality: "أورغواي",
    },
    {
      id: "c95bcac8-890c-480a-a9f6-d2e7d13c0df8",
      country_code: "UM",
      country_enName: "US Minor Outlying Islands",
      country_arName: "قائمة الولايات والمناطق الأمريكية",
      country_enNationality: "US Minor Outlying Islander",
      country_arNationality: "أمريكي",
    },
    {
      id: "7e467486-01a5-4336-ac03-d40a9f46b769",
      country_code: "TF",
      country_enName: "French Southern and Antarctic Lands",
      country_arName: "أراض فرنسية جنوبية وأنتارتيكية",
      country_enNationality: "French",
      country_arNationality: "أراض فرنسية جنوبية وأنتارتيكية",
    },
    {
      id: "4103f3dd-32c9-4fc9-9728-d707d86194a1",
      country_code: "GB",
      country_enName: "United Kingdom",
      country_arName: "المملكة المتحدة",
      country_enNationality: "British",
      country_arNationality: "بريطاني",
    },
    {
      id: "e4865a76-2707-472d-9176-d77f949ea34a",
      country_code: "BD",
      country_enName: "Bangladesh",
      country_arName: "بنغلاديش",
      country_enNationality: "Bangladeshi",
      country_arNationality: "بنغلاديشي",
    },
    {
      id: "72a83b3b-3b19-42ad-bd03-dae984493f95",
      country_code: "IR",
      country_enName: "Iran",
      country_arName: "إيران",
      country_enNationality: "Iranian",
      country_arNationality: "إيراني",
    },
    {
      id: "91109b23-6834-49cc-bafa-db379381343e",
      country_code: "LI",
      country_enName: "Liechtenstein",
      country_arName: "ليختنشتين",
      country_enNationality: "Liechtenstein",
      country_arNationality: "ليختنشتيني",
    },
    {
      id: "11c632cf-9afa-43f3-a828-dc4ee6ab1310",
      country_code: "SS",
      country_enName: "South Sudan",
      country_arName: "السودان الجنوبي",
      country_enNationality: "South Sudanese",
      country_arNationality: "سوادني جنوبي",
    },
    {
      id: "cf7a774b-d782-450b-9cd5-ddaa752f5b91",
      country_code: "IQ",
      country_enName: "Iraq",
      country_arName: "العراق",
      country_enNationality: "Iraqi",
      country_arNationality: "عراقي",
    },
    {
      id: "25864159-e0d3-4f57-89df-ddd030712d46",
      country_code: "TK",
      country_enName: "Tokelau",
      country_arName: "توكيلاو",
      country_enNationality: "Tokelaian",
      country_arNationality: "توكيلاوي",
    },
    {
      id: "3efe709b-4ba4-4b75-9d62-de05651ba7e1",
      country_code: "MP",
      country_enName: "Northern Mariana Islands",
      country_arName: "جزر ماريانا الشمالية",
      country_enNationality: "Northern Marianan",
      country_arNationality: "ماريني",
    },
    {
      id: "842180a5-7a5e-4175-8f68-de3538e8af90",
      country_code: "HT",
      country_enName: "Haiti",
      country_arName: "هايتي",
      country_enNationality: "Haitian",
      country_arNationality: "هايتي",
    },
    {
      id: "e227d18e-453a-4dfa-a88d-e0f6f4719ec9",
      country_code: "FK",
      country_enName: "Falkland Islands (Malvinas)",
      country_arName: "جزر فوكلاند",
      country_enNationality: "Falkland Islander",
      country_arNationality: "فوكلاندي",
    },
    {
      id: "442c5f69-4632-453e-a529-e15f1afe5962",
      country_code: "GN",
      country_enName: "Guinea",
      country_arName: "غينيا",
      country_enNationality: "Guinean",
      country_arNationality: "غيني",
    },
    {
      id: "177d8409-ed6c-4e99-a7f7-e22b79588c95",
      country_code: "IS",
      country_enName: "Iceland",
      country_arName: "آيسلندا",
      country_enNationality: "Icelandic",
      country_arNationality: "آيسلندي",
    },
    {
      id: "27389cce-308d-46c8-9786-e51e0381d94f",
      country_code: "WF",
      country_enName: "Wallis and Futuna Islands",
      country_arName: "والس وفوتونا",
      country_enNationality: "Wallisian/Futunan",
      country_arNationality: "فوتوني",
    },
    {
      id: "a30192dd-34d4-40f4-9bc2-e647083348d2",
      country_code: "PA",
      country_enName: "Panama",
      country_arName: "بنما",
      country_enNationality: "Panamanian",
      country_arNationality: "بنمي",
    },
    {
      id: "84c1e473-6143-4ee8-921a-e90210e5e096",
      country_code: "JE",
      country_enName: "Jersey",
      country_arName: "جيرزي",
      country_enNationality: "Jersian",
      country_arNationality: "جيرزي",
    },
    {
      id: "3dc2db60-fdff-414a-ae8c-e983825be6fa",
      country_code: "CW",
      country_enName: "Curaçao",
      country_arName: "كوراساو",
      country_enNationality: "Curacian",
      country_arNationality: "كوراساوي",
    },
    {
      id: "e287ddbb-939f-4cb0-896f-e9ab213e25bd",
      country_code: "RO",
      country_enName: "Romania",
      country_arName: "رومانيا",
      country_enNationality: "Romanian",
      country_arNationality: "روماني",
    },
    {
      id: "dd29e61b-cd74-4419-a67e-ea323f8c0be7",
      country_code: "TH",
      country_enName: "Thailand",
      country_arName: "تايلندا",
      country_enNationality: "Thai",
      country_arNationality: "تايلندي",
    },
    {
      id: "623c2fc0-3046-4011-916c-ea6c29306c4f",
      country_code: "WS",
      country_enName: "Samoa",
      country_arName: "ساموا",
      country_enNationality: "Samoan",
      country_arNationality: "ساموي",
    },
    {
      id: "dba04242-84a2-4542-b1ca-eb45aabd5652",
      country_code: "TM",
      country_enName: "Turkmenistan",
      country_arName: "تركمانستان",
      country_enNationality: "Turkmen",
      country_arNationality: "تركمانستاني",
    },
    {
      id: "10819752-6ac6-4c90-a6be-ec08d9346523",
      country_code: "TD",
      country_enName: "Chad",
      country_arName: "تشاد",
      country_enNationality: "Chadian",
      country_arNationality: "تشادي",
    },
    {
      id: "e29c4995-b800-4d65-ab6d-ec190dcd272d",
      country_code: "ST",
      country_enName: "Sao Tome and Principe",
      country_arName: "ساو تومي وبرينسيبي",
      country_enNationality: "Sao Tomean",
      country_arNationality: "ساو تومي وبرينسيبي",
    },
    {
      id: "7d718b20-e1d7-4bbf-af62-ec9d9baffd43",
      country_code: "VC",
      country_enName: "Saint Vincent and the Grenadines",
      country_arName: "سانت فنسنت وجزر غرينادين",
      country_enNationality: "Saint Vincent and the Grenadines",
      country_arNationality: "سانت فنسنت وجزر غرينادين",
    },
    {
      id: "87c9a3bf-ed25-445f-82da-f10491d17022",
      country_code: "FO",
      country_enName: "Faroe Islands",
      country_arName: "جزر فارو",
      country_enNationality: "Faroese",
      country_arNationality: "جزر فارو",
    },
    {
      id: "3053da85-904f-4ecf-85ff-f138ea476115",
      country_code: "PG",
      country_enName: "Papua New Guinea",
      country_arName: "بابوا غينيا الجديدة",
      country_enNationality: "Papua New Guinean",
      country_arNationality: "بابوي",
    },
    {
      id: "50356a59-5814-4fc3-a4f5-f16ec3f491be",
      country_code: "MU",
      country_enName: "Mauritius",
      country_arName: "موريشيوس",
      country_enNationality: "Mauritian",
      country_arNationality: "موريشيوسي",
    },
    {
      id: "c32c567f-d35c-40b1-b51c-f239850fe52e",
      country_code: "GF",
      country_enName: "French Guiana",
      country_arName: "غويانا الفرنسية",
      country_enNationality: "French Guianese",
      country_arNationality: "غويانا الفرنسية",
    },
    {
      id: "61dbfeec-6fe3-4aca-83d6-f45ac4224b09",
      country_code: "MG",
      country_enName: "Madagascar",
      country_arName: "مدغشقر",
      country_enNationality: "Malagasy",
      country_arNationality: "مدغشقري",
    },
    {
      id: "dc0fff1f-c9a6-474e-b4c1-f4648eb6bd85",
      country_code: "NZ",
      country_enName: "New Zealand",
      country_arName: "نيوزيلندا",
      country_enNationality: "New Zealander",
      country_arNationality: "نيوزيلندي",
    },
    {
      id: "0e53130f-ab45-4320-942f-f4e9f4e67d47",
      country_code: "FR",
      country_enName: "France",
      country_arName: "فرنسا",
      country_enNationality: "French",
      country_arNationality: "فرنسي",
    },
    {
      id: "e0e5224a-a6d0-4e29-b376-f560caa49652",
      country_code: "CC",
      country_enName: "Cocos (Keeling) Islands",
      country_arName: "جزر كوكوس",
      country_enNationality: "Cocos Islander",
      country_arNationality: "جزر كوكوس",
    },
    {
      id: "7de89773-824a-49fe-92f4-f7fa085af76b",
      country_code: "FM",
      country_enName: "Micronesia",
      country_arName: "مايكرونيزيا",
      country_enNationality: "Micronesian",
      country_arNationality: "مايكرونيزيي",
    },
    {
      id: "cdeafee1-2ec7-4fcf-98a6-f85449358ffd",
      country_code: "TN",
      country_enName: "Tunisia",
      country_arName: "تونس",
      country_enNationality: "Tunisian",
      country_arNationality: "تونسي",
    },
    {
      id: "4d6ca8cb-ef56-47e3-b7e1-f906bee16c8f",
      country_code: "MZ",
      country_enName: "Mozambique",
      country_arName: "موزمبيق",
      country_enNationality: "Mozambican",
      country_arNationality: "موزمبيقي",
    },
    {
      id: "8df68800-2b32-4734-8fdf-f968083197c0",
      country_code: "TZ",
      country_enName: "Tanzania",
      country_arName: "تنزانيا",
      country_enNationality: "Tanzanian",
      country_arNationality: "تنزانيي",
    },
    {
      id: "b967a59a-f6c2-4458-ad1c-fb2f8a10b082",
      country_code: "EH",
      country_enName: "Western Sahara",
      country_arName: "الصحراء الغربية",
      country_enNationality: "Sahrawian",
      country_arNationality: "صحراوي",
    },
    {
      id: "c90c00ca-c714-4383-906a-fc074e73cbde",
      country_code: "LV",
      country_enName: "Latvia",
      country_arName: "لاتفيا",
      country_enNationality: "Latvian",
      country_arNationality: "لاتيفي",
    },
    {
      id: "019fdb15-af13-4ead-885f-fc99d0d02cb2",
      country_code: "KW",
      country_enName: "Kuwait",
      country_arName: "الكويت",
      country_enNationality: "Kuwaiti",
      country_arNationality: "كويتي",
    },
    {
      id: "2bb06a1f-26f0-4f40-8e17-fdd2f05b1f1e",
      country_code: "PR",
      country_enName: "Puerto Rico",
      country_arName: "بورتو ريكو",
      country_enNationality: "Puerto Rican",
      country_arNationality: "بورتي",
    },
    {
      id: "82f07f4c-c3ec-432a-8713-ff8da56eac2c",
      country_code: "RE",
      country_enName: "Reunion Island",
      country_arName: "ريونيون",
      country_enNationality: "Reunionese",
      country_arNationality: "ريونيوني",
    },
  ],
};
var tNationalits = [];
var tEmirates = [];
var emirates = {
  em: [
    {
      disabled: false,
      group: null,
      selected: false,
      text: "Abu Dhabi | أبو ظبي",
      value: "Abu Dhabi",
    },
    {
      disabled: false,
      group: null,
      selected: false,
      text: "Dubai | دبي",
      value: "Dubai",
    },
    {
      disabled: false,
      group: null,
      selected: false,
      text: "Sharjah | الشارقة",
      value: "Sharjah",
    },
    {
      disabled: false,
      group: null,
      selected: false,
      text: "Ajman | عجمان",
      value: "Ajman",
    },
    {
      disabled: false,
      group: null,
      selected: false,
      text: "Umm Al Quwain | أم القوين",
      value: "Umm Al Quwain",
    },
    {
      disabled: false,
      group: null,
      selected: false,
      text: "Ras Al Khaimah | راس الخيمة",
      value: "Ras Al Khaimah",
    },
    {
      disabled: false,
      group: null,
      selected: false,
      text: "Fujairah | الفجيرة",
      value: "Fujairah",
    },
  ],
};
